syntax = "proto3";

package library.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service BookService {
  rpc GetBook(GetBookRequest) returns (Book) {
    option (google.api.http) = {get: "/v1/{name=books/*}"};
  }
  rpc ListBooks(ListBooksRequest) returns (ListBooksResponse);
}

message Book {
  string name = 1;
  string title = 2;
  google.protobuf.Timestamp created_at = 3;
}

message GetBookRequest {
  string name = 1;
}

message ListBooksRequest {
  int32 limit = 1;
}

message ListBooksResponse {
  repeated Book books = 1;
}
